import { RecordedClass } from "../types";

export const SAMPLE_RECORDED_CLASSES: RecordedClass[] = [
  {
    id: "rec-1",
    title: "Introduction to React Hooks",
    course: "CS 4350 - Software Engineering",
    instructor: "Dr. Sarah Johnson",
    recordedDate: "2025-10-05T14:00:00Z",
    duration: 85,
    type: "lecture",
    participants: 28,
    views: 1247,
    description:
      "Comprehensive introduction to React Hooks including useState, useEffect, and custom hooks with practical examples.",
    videoUrl: "https://youtu.be/9c7zh2MkslY?si=zdwMoz5g2twzcO4n",
    downloadUrl: "/downloads/react-hooks-intro.mp4",
    tags: ["React", "Hooks", "JavaScript", "Frontend"],
    quality: "FHD",
    fileSize: "1.2 GB",
  },
  {
    id: "rec-2",
    title: "Database Normalization Workshop",
    course: "CS 3380 - Database Systems",
    instructor: "Prof. Michael Chen",
    recordedDate: "2025-10-03T10:00:00Z",
    duration: 110,
    type: "workshop",
    participants: 22,
    views: 856,
    description:
      "Hands-on workshop covering database normalization forms, practical exercises with real-world examples.",
    videoUrl: "https://youtu.be/9c7zh2MkslY?si=zdwMoz5g2twzcO4n",
    downloadUrl: "/downloads/db-normalization.mp4",
    tags: ["Database", "Normalization", "SQL", "Design"],
    quality: "HD",
    fileSize: "950 MB",
  },
  {
    id: "rec-3",
    title: "Machine Learning Algorithms Deep Dive",
    course: "CS 4385 - Machine Learning",
    instructor: "Dr. Emily Rodriguez",
    recordedDate: "2025-09-28T16:00:00Z",
    duration: 165,
    type: "lab",
    participants: 15,
    views: 2103,
    description:
      "Detailed exploration of classification algorithms including decision trees, random forests, and SVM implementations.",
    videoUrl: "https://youtu.be/9c7zh2MkslY?si=zdwMoz5g2twzcO4n",
    downloadUrl: "/downloads/ml-algorithms.mp4",
    tags: ["Machine Learning", "Algorithms", "Python", "Classification"],
    quality: "4K",
    fileSize: "2.8 GB",
  },
  {
    id: "rec-4",
    title: "Advanced JavaScript Concepts",
    course: "CS 3345 - Web Programming",
    instructor: "Prof. David Wilson",
    recordedDate: "2025-09-25T13:00:00Z",
    duration: 95,
    type: "lecture",
    participants: 31,
    views: 1678,
    description:
      "Advanced JavaScript topics including closures, prototypes, async/await, and modern ES6+ features.",
    videoUrl: "https://youtu.be/9c7zh2MkslY?si=zdwMoz5g2twzcO4n",
    downloadUrl: "/downloads/advanced-js.mp4",
    tags: ["JavaScript", "ES6", "Async", "Closures"],
    quality: "FHD",
    fileSize: "1.4 GB",
  },
  {
    id: "rec-5",
    title: "Software Architecture Patterns",
    course: "CS 4350 - Software Engineering",
    instructor: "Dr. Sarah Johnson",
    recordedDate: "2025-09-20T11:00:00Z",
    duration: 120,
    type: "lecture",
    participants: 26,
    views: 945,
    description:
      "Overview of common software architecture patterns including MVC, MVP, MVVM, and microservices architecture.",
    videoUrl: "https://youtu.be/9c7zh2MkslY?si=zdwMoz5g2twzcO4n",
    downloadUrl: "/downloads/architecture-patterns.mp4",
    tags: ["Architecture", "Patterns", "Design", "Software Engineering"],
    quality: "FHD",
    fileSize: "1.6 GB",
  },
];
